services:
  cocaagri-census:
    image: agri-census:${TAG}
    container_name: agri-census
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "8502:8501"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/agri-census/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped